services:
  gateway:
    build: ./Gateway
    ports:
      - "5000:80"
    depends_on:
      - authservice
      - chatservice

  authservice:
    build: ./AuthService
    environment:
      - Jwt__Key=supersecretkey1234567890
      - Jwt__Issuer=Gateway
      - Jwt__Audience=Microservices

  chatservice:
    build: ./ChatService
    environment:
      - ConnectionStrings__DefaultConnection=Server=mssql;Database=ChatDb;User=sa;Password=YourStrong@Passw0rd;
      - Redis__Connection=redis:6379
    depends_on:
      - mssql
      - redis

  presenceservice:
    build: ./PresenceService
    environment:
      - Redis__Connection=redis:6379
    depends_on:
      - redis

  notificationservice:
    build: ./NotificationService
    environment:
      - Smtp__Host=smtp
      - Smtp__Port=1025
      - Smtp__From=notifications@messenger.com
      - ConnectionStrings__DefaultConnection=Server=mssql;Database=ChatDb;User=sa;Password=YourStrong@Passw0rd;
      - Redis__Connection=redis:6379
    depends_on:
      - mssql
      - redis
      - smtp

  mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: "YourStrong@Passw0rd"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"

  redis:
    image: redis:5.0
    ports:
      - "6379:6379"

  smtp:
    image: maildev/maildev
    ports:
      - "1080:1080"
      - "1025:1025"