version: '3.8'

services:
  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: chat-ecosystem-db
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Your_password123
    ports:
      - "5400:1433"
    healthcheck:
      test: ["CMD-SHELL", "sqlcmd -S localhost -U sa -P Your_password123 -Q 'SELECT 1' || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

  auth-api:
    build:
      context: .
      dockerfile: AuthService/ChatEcoSystem.Auth.Api/Dockerfile
    container_name: chat-ecosystem-auth-api
    env_file:
      - auth-service.env
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "5000:5000"
      - "5001:5001" 